---
- name: Example Playbook with ipaddr filter
  hosts: localhost
  gather_facts: false
  vars:
    ip_address: "192.168.1.1"

  tasks:
    - name: Extract network address from the IP
      debug:
        msg: "{{ ip_address | ipaddr('network') }}"

    - name: Check if the IP is in a specific network
      debug:
        msg: "IP is in the specified network"
      when: ip_address | ipaddr('network') == '192.168.1.0/24'